sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script: npm run travis

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success: cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose &&
    rm -rf ./coverage

dist: precise
